# Generated by Django 4.1.2 on 2022-11-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
